# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "larryli/utopic64"

  config.vm.define "web" do |web|

    web.vm.network "forwarded_port",
      guest: 80, host: 8080

    web.vm.provision "ansible" do |ansible|
      ansible.playbook = "../roles/web.yml"
      ansible.sudo = true
    end
  end

  config.vm.define "db" do |db|

    db.vm.network "forwarded_port",
      guest: 5432, host: 5432

    db.vm.provision "ansible" do |ansible|
      ansible.playbook = "../roles/db.yml"
      ansible.sudo = true
    end
  end

end
